# Generated by Django 2.0 on 2018-03-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
