# Generated by Django 2.0 on 2018-03-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_backend', '0002_tweet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='query',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
