# Generated by Django 2.0 on 2018-03-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_backend', '0003_tweet_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.BigIntegerField(),
        ),
    ]
