# Generated by Django 2.0 on 2018-03-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_backend', '0004_auto_20180319_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
